openapi: 3.0.3
info:
  title: k1-k2-k3 API
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Vérifie que le serveur est actif
      responses:
        '200':
          description: Pong
          content:
            text/plain:
              schema:
                type: string
  /home:
    get:
      summary: Page d'accueil HTML
      responses:
        '200':
          description: Page HTML d'accueil
          content:
            text/html:
              schema:
                type: string
  /posts:
    post:
      summary: Crée de nouveaux posts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  author:
                    type: string
                  title:
                    type: string
                  content:
                    type: string
                  creation_datetime:
                    type: string
      responses:
        '201':
          description: Posts créés avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    author:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
                    creation_datetime:
                      type: string
    get:
      summary: Récupère tous les posts
      responses:
        '200':
          description: Liste des posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    author:
                      type: string
                    title:
                      type: string
                    content:
                      type: string
                    creation_datetime:
                      type: string
