openapi: 3.0.3
info:
  title: k4-k5 API
  version: 1.0.0
paths: 
  /hello:
    get:
      summary: Retourne un message Hello world!
      responses:
        '200':
          description: Message texte simple
          content:
            text/plain:
              schema:
                type: string
  /welcome:
    get:
      summary: Retourne un message de bienvenue avec le nom fourni
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Message de bienvenue
          content:
            text/plain:
              schema:
                type: string
